version: '3'
services:
  server:
    build: .
    depends_on:
      - mongo
    ports:
      - 8080:8080

  dev:
    image: cosmtrek/air:v1.40.4
    depends_on:
      - mongo
    working_dir: "/server"
    environment:
      air_wd: "/server"
    volumes:
      - .:/server
    ports:
      - 8080:8080
    command: air -c .air.toml

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my_fancy_password
