version: '3'
services:
  server:
    build: .
    depends_on:
      - mysql
    ports:
      - 8080:8080

  dev:
    image: cosmtrek/air:v1.40.4
    depends_on:
      - mysql
    working_dir: "/server"
    environment:
      air_wd: "/server"
    volumes:
      - .:/server
    ports:
      - 8080:8080
    command: air -c .air.toml

  mysql:
    image: mysql:latest
